### PR TITLE
removed crash when duplicate word was getting added and updated the b…

### PR DESCRIPTION
**Pull request by amit-bhandari**
…uild tools version and gradle version

### CODE REVIEW

**Comment by amit-bhandari** [comment]
Verified email id

**Comment by abedinzhuniqi** [comment]
For the moment it is saving the data and showing in recycler view list but the problem it is when you exit the app and again open the data are not there.

**Comment by florina-muntenescu** [comment]
Would you mind rebasing an updating to the latest versions, similar to the kotlin branch, please?
Also, could you double check that everything is ok with the CLA?

**Comment by amit-bhandari** [comment]
Done!
I don't know why CLA is failing, it didn't fail in my kotlin branch pull request.
@florina-muntenescu Could you please check and merge, thanks!

**Comment by florina-muntenescu** [comment]
Fixed in #18 
Thank you for the PR

**Pull request closed without merging**
